### ISSUE TITLE
Borders don't work anymore

### ISSUE THREAD

**Issue by PaulRambags** [braillespecs/braille-css#48]
I was not able to produce borders with this version of the pipeline:

```
    <parent>
        <groupId>org.daisy.pipeline.modules.braille</groupId>
        <artifactId>braille-modules-parent</artifactId>
        <version>1.11.3-SNAPSHOT</version>
        <relativePath />
    </parent>
 
```
Is the border functionality broken?

**Comment by bertfrees** [comment]
Can you please provide a test and then open an issue in https://github.com/daisy/pipeline-mod-braille/issues? (This repo is for the CSS specification.)
